### ISSUE TITLE
Pre-Footer : Client Testimonial container is not perfectly aligned.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Pace-Henley#19]
![image](https://cloud.githubusercontent.com/assets/12791909/12284620/0e3d499c-b9ec-11e5-922b-5d615b89ef09.png)

**Comment by ermatitan** [comment]
not fix on Microsoft Edge browser

**Comment by ermatitan** [comment]
still not fix

**Comment by Santosh-titan** [comment]
Strange its working fine for IE edge here. see screenshot
![ie-edge](https://cloud.githubusercontent.com/assets/13828562/12605208/c572d940-c4e8-11e5-8240-9dce8ea2a697.jpg)

**Comment by ermatitan** [comment]
Strange 'coz i can still see the issue
![image](https://cloud.githubusercontent.com/assets/12791909/12635814/3ace2954-c5c2-11e5-98c4-82b0a7887513.png)
