### ISSUE TITLE
Pre-Footer: Fax Number value has underlined text decoration on Microsoft Edge.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Pace-Henley#34]
Browser: Microsoft Edge

![image](https://cloud.githubusercontent.com/assets/12791909/12286767/21237d5e-ba02-11e5-9af7-316b9da5650a.png)

**Comment by Santosh-titan** [comment]
Its working fine for me.

**Comment by ermatitan** [comment]
Not working on my end. This is only occur in Microsoft Edge browser.

**Comment by Santosh-titan** [comment]
Same issue was occur in my previous project, Jonathan said its was won't fix bug. because its doesn't have border and anchor but It is still displaying border.
Note : this was happening only for fax number.
