### ISSUE TITLE
Mobile: Banner left navigation button overlaps with banner title and content.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Pace-Henley#38]
S4 , iTouch 

![image](https://cloud.githubusercontent.com/assets/12791909/12312341/a75bc7b8-ba99-11e5-96ba-bc62be521dab.png)

**Comment by ermatitan** [comment]
problem also occurs on Ipad Air

**Comment by Santosh-titan** [comment]
Better we should remove arrow icon for devices. because there is no enough space to align arrow icons.Please suggest

**Comment by ermatitan** [comment]
It is already fix in small devices (itouch and S4) 
Problem still fix on Ipad Air in both portrait and landscape. Ipad has bigger screen size so i think there is no need to remove the arrow icons. Thank you
